Rework output modes
Add a bunch of tests defining various output modes, which previously were
untested and a bit amorphous.  This changes numerous options.

diff --git a/bin/ts b/bin/ts
--- a/bin/ts
+++ b/bin/ts
@@ -3,36 +3,34 @@
 ts_progname="${0##*/}"
 ts_version="1.0"
 ts_author="Simon Chiang"
-ts_usage="usage: %s [-c] [-d] [-f] [-h] [-r] [-t TS_TMP_DIR] [-v] %s\n"
+ts_usage="usage: %s [-acfhrsv] [-t TS_TMP_DIR] %s\n"
 if [ "ts" = "$ts_progname" ]
 then ts_args="[TEST_FILES...]"
 else ts_args="[TEST_NAMES...]"
 fi
 ts_opt="       %s   %s\n"
 
-while getopts "cdfhlmn:rt:v" ts_option
+while getopts "achmrst:v" ts_option
 do
   case $ts_option in
-    c  )  ts_cleanup=true ;;
-    d  )  ts_debug=true ;;
-    f  )  ts_format=true ;;
+    a  )  TS_FILTER=false ;;
+    c  )  TS_COLOR=true ;;
     h  )  printf "$ts_usage" "$ts_progname" "$ts_args"
-          printf "$ts_opt" "-c" "cleanup tmp dir on complete"
-          printf "$ts_opt" "-d" "debug mode"
-          printf "$ts_opt" "-f" "format output"
+          printf "$ts_opt" "-a" "show all tests"
+          printf "$ts_opt" "-c" "color output"
           printf "$ts_opt" "-h" "prints this help"
           printf "$ts_opt" "-m" "monitor output"
-          printf "$ts_opt" "-r" "raw output (overrides -fmv)"
+          printf "$ts_opt" "-r" "raw output (overrides -cms)"
+          printf "$ts_opt" "-s" "stream output"
           printf "$ts_opt" "-t" "set the test tmp dir (default tmp)"
-          printf "$ts_opt" "-v" "verbose output (show passing tests)"
+          printf "$ts_opt" "-v" "verbose output (show stderr)"
           printf "\n"
           exit 0 ;;
-    l  )  ts_list=true ;;
-    m  )  ts_monitor=true ;;
-    n  )  TS_NAME=$OPTARG ;;
-    r  )  ts_raw=true ;;
+    m  )  TS_REPORT=monitor ;;
+    r  )  TS_REPORT=raw ;;
+    s  )  TS_REPORT=stream ;;
     t  )  TS_TMP_DIR=$OPTARG ;;
-    v  )  ts_verbose=true ;;
+    v  )  TS_MODE=verbose ;;
     \? )  printf "$ts_usage" "$ts_progname" "$ts_args"
           exit 2 ;;
   esac
@@ -42,14 +40,19 @@ shift $(($OPTIND - 1))
 TS_USR_DIR="${TS_USR_DIR:-$(pwd)}"
 TS_TMP_DIR="${TS_TMP_DIR:-$TS_USR_DIR/tmp}"
 
-mkdir -p "$TS_TMP_DIR"
-ts_stat_file="$TS_TMP_DIR/stat"
-ts_mon_file="$TS_TMP_DIR/mon"
+TS_COLOR=${TS_COLOR:-false}
+TS_FILTER=${TS_FILTER:-true}
+TS_REPORT=${TS_REPORT:-monitor}
+TS_MODE=${TS_MODE:-normal}
 
 TS_PASS="${TS_PASS:-[32m}"
 TS_FAIL="${TS_FAIL:-[1;31m}"
 TS_NORM="${TS_NORM:-[0m}"
 TS_NOEX="${TS_NOEX:-[1;33m}"
+
+mkdir -p "$TS_TMP_DIR"
+ts_status_file="$TS_TMP_DIR/status"
+ts_monitor_file="$TS_TMP_DIR/monitor"
 
 ############################################################################
 # private functions
@@ -62,7 +65,8 @@ ts_list () {
 }
 
 ts_structure () {
-  awk '
+  rm "$ts_status_file" 2>/dev/null
+  awk -v status_file="$ts_status_file" '
 function readbytes (bytes) {
   # account for trailing 'x'
   bytes -= 1
@@ -83,91 +87,97 @@ function readbytes (bytes) {
   }
 }
 
-BEGIN   { npass=nfail=0 }
-/^\[/   { print }
-/^P/    { readbytes($2); npass++; printf "P\n" }
-/^F/    { readbytes($2); nfail++; printf "F\n" }
-/^X/    { readbytes($2); nfail++; printf "X\n" }
-END     { printf "%d %d", npass, nfail > "'"$ts_stat_file"'" }
+BEGIN { npass=nfail=0 }
+/^\[/ { descr=$0 }
+/^P/  { printf("P %s\n", descr); readbytes($2); npass++; printf("\n") }
+/^F/  { printf("F %s\n", descr); readbytes($2); nfail++; printf("\n") }
+/^X/  { printf("X %s\n", descr); readbytes($2); nfail++; printf("\n") }
+END   { printf("%d %d\n", npass, nfail) >> status_file }
 '
 }
 
 ts_monitor () {
-  if [ "true" = "$ts_monitor" ]
-  then
-    sed -lne "
-w $ts_mon_file
-/P\$/a\\
+  rm "$ts_monitor_file" 2> /dev/null
+  sed -lne "
+w $ts_monitor_file
+/^P/a\\
 .
-/F\$/a\\
+/^F/a\\
 F
-/X\$/a\\
+/^X/a\\
 -
 " | tr -ud "\n" >&2
-    printf "\n" >&2
-    cat "$ts_mon_file"
-  else cat
-  fi
-}
+  printf "\n\n" >&2
 
-ts_format () {
-  if [ "true" = "$ts_format" ]
-  then sed -lne "
-/^\[/ {
-x
-d
-}
-H
-/^[PFX]/ {
-x
-/P\$/ s/^\[\([^]]*\)/[$TS_PASS\1$TS_NORM/
-/F\$/ s/^\[\([^]]*\)/[$TS_FAIL\1$TS_NORM/
-/X\$/ s/^\[\([^]]*\)/[$TS_NOEX\1$TS_NORM/
-s/[PFX]\$//
-p
-}
-"
-  else cat
-  fi
+  cat "$ts_monitor_file"
 }
 
 ts_filter () {
-  if [ "true" = "$ts_verbose" ]
-  then cat
-  else sed -lne "
-/^\[/ {
-x
-d
-}
+  if [ "true" = "$TS_FILTER" ]
+  then sed -lne "
 H
-/^[PFX]/ {
+/^$/ {
 x
-/[FX]\$/ p
+s/^\n\([FX]\)/\1/p
 }
 "
+  else cat
   fi
+}
+
+ts_color () {
+  if [ "true" = "$TS_COLOR" ]
+  then sed -lne "
+s/^P \[\([^]]*\)/[$TS_PASS\1$TS_NORM/
+s/^F \[\([^]]*\)/[$TS_FAIL\1$TS_NORM/
+s/^X \[\([^]]*\)/[$TS_NOEX\1$TS_NORM/
+p
+"
+  else cat
+  fi
+}
+
+ts_color_or_format () {
+  if [ "true" = "$TS_COLOR" ]
+  then ts_color
+  else sed -le '
+/^[PFX]/ {
+  h
+  s/^[PFX] //
+}
+/^$/ {
+  g
+  s/^\([PFX]\).*$/\1\
+/
+}
+'
+  fi
+}
+
+ts_check_status () {
+  awk -v nsec="$1" '
+BEGIN { npass=nfail=0 }
+      { npass += $1; nfail += $2; }
+END   { printf("%d pass %d fail %d s\n", npass, nfail, nsec); if(nfail > 0) exit 1 }
+' < "$ts_status_file"
 }
 
 ts_report () {
-  ts_start_time=$SECONDS
-  if [ "true" = "$ts_raw" ]
-  then cat
-  else
-    ts_structure "$ts_stat_file" |
-    ts_monitor "$ts_mon_file" |
-    ts_filter |
-    ts_format
-  fi
-  ts_end_time=$SECONDS
-
-  if [ "true" != "$ts_raw" ]
-  then
-    cat "$ts_stat_file" | awk -v time="$(($ts_end_time - $ts_start_time))" '{
-      npass=$1; nfail=$2
-      printf "%d pass %d fail %d s\n", npass, nfail, time
-      if(nfail > 0) exit 1;
-    }' >&2
-  fi
+  case "$TS_REPORT" in
+    (monitor)
+      ts_start_time=$SECONDS
+      ts_structure | ts_monitor | ts_filter | ts_color_or_format
+      ts_end_time=$SECONDS
+      ts_check_status "$(($ts_end_time - $ts_start_time))" >&2
+      ;;
+    (stream)
+      ts_structure | ts_filter | ts_color
+      ts_check_status > /dev/null
+      ;;
+    (raw)
+      cat
+      ;;
+  esac
 }
 
 # Runs a specific test.  In that case the test output is not filtered or
@@ -196,6 +206,7 @@ ts_run_test_suite () {
   while read test_lineno test_name junk
   do
     test_dir="$TS_TMP_DIR/$test_case/$test_name"
+    printf "[%s:%s] %s\n" "$test_file" "$test_lineno" "$test_name"
 
     # run the test by calling back into the test file
     # * use stdout for progress, stderr for debug information
@@ -204,7 +215,7 @@ ts_run_test_suite () {
     # * use a subprocess to prevent leakage (ex set -x)
     # * append x to preserve trailing newline
     if ts_stdout=$(
-      if [ "true" = "$ts_debug" ]
+      if [ "verbose" = "$TS_MODE" ]
       then (ts_run_test 2>&1)
       else (ts_run_test 2>/dev/null)
       fi
@@ -216,14 +227,17 @@ ts_run_test_suite () {
     else ts_status=F
     fi
 
-    printf "[%s:%s] %s\n%s %d\n%s\n" "$test_file" "$test_lineno" "$test_name" "$ts_status" "${#ts_stdout}" "$ts_stdout"
-  done  | ts_report
+    printf "%s %d\n%s\n" "$ts_status" "${#ts_stdout}" "$ts_stdout"
+  done | ts_report
 }
 
 ts_run_test_files () {
   export TS_USR_DIR
   export TS_TMP_DIR
-  export TS_NAME
+
+  export TS_COLOR
+  export TS_FILTER
+  export TS_MODE
 
   for test_file in "$@"
   do
