use ts prefix for internal variables and functions

diff --git a/bin/ts b/bin/ts
--- a/bin/ts
+++ b/bin/ts
@@ -1,39 +1,39 @@
 #!/bin/bash
 ############################################################################
-version="1.0"
-author="Simon Chiang"
+ts_version="1.0"
+ts_author="Simon Chiang"
 
-usage="usage: %s [-c] [-d] [-f] [-h] [-l] [-r] [-t TS_TMP_DIR] [-v] %s%s\n"
-args="[TEST_FILES...]"
-args="${args:-[TEST_NAMES...]}"
-progname="${0##*/}"
-opt="       %s   %s\n"
+ts_usage="usage: %s [-c] [-d] [-f] [-h] [-l] [-r] [-t TS_TMP_DIR] [-v] %s\n"
+ts_args="[TEST_FILES...]"
+ts_args="${ts_args:-[TEST_NAMES...]}"
+ts_progname="${0##*/}"
+ts_opt="       %s   %s\n"
 
-while getopts "cdfhlmn:rt:v" option
+while getopts "cdfhlmn:rt:v" ts_option
 do
-  case $option in
-    c  )  cleanup=true ;;
-    d  )  debug=true ;;
-    f  )  format=true ;;
-    h  )  printf "$usage" "$progname" "$args" "$doc"
-          printf "$opt" "-c" "cleanup tmp dir on complete"
-          printf "$opt" "-d" "debug mode"
-          printf "$opt" "-f" "format output"
-          printf "$opt" "-h" "prints this help"
-          printf "$opt" "-l" "list the tests to be run"
-          printf "$opt" "-m" "monitor output"
-          printf "$opt" "-r" "raw output (overrides -fmv)"
-          printf "$opt" "-t" "set the test tmp dir (default tmp)"
-          printf "$opt" "-v" "verbose output (show passing tests)"
+  case $ts_option in
+    c  )  ts_cleanup=true ;;
+    d  )  ts_debug=true ;;
+    f  )  ts_format=true ;;
+    h  )  printf "$ts_usage" "$ts_progname" "$ts_args"
+          printf "$ts_opt" "-c" "cleanup tmp dir on complete"
+          printf "$ts_opt" "-d" "debug mode"
+          printf "$ts_opt" "-f" "format output"
+          printf "$ts_opt" "-h" "prints this help"
+          printf "$ts_opt" "-l" "list the tests to be run"
+          printf "$ts_opt" "-m" "monitor output"
+          printf "$ts_opt" "-r" "raw output (overrides -fmv)"
+          printf "$ts_opt" "-t" "set the test tmp dir (default tmp)"
+          printf "$ts_opt" "-v" "verbose output (show passing tests)"
           printf "\n"
           exit 0 ;;
-    l  )  list=true ;;
-    m  )  monitor=true ;;
+    l  )  ts_list=true ;;
+    m  )  ts_monitor=true ;;
     n  )  TS_NAME=$OPTARG ;;
-    r  )  raw=true ;;
+    r  )  ts_raw=true ;;
     t  )  TS_TMP_DIR=$OPTARG ;;
-    v  )  verbose=true ;;
-    \? )  printf "$usage" "$0" "$args"
+    v  )  ts_verbose=true ;;
+    \? )  printf "$ts_usage" "$ts_progname" "$ts_args"
           exit 2 ;;
   esac
 done
@@ -127,7 +127,7 @@ assert_match () {
 
 ############################################################################
 
-ts_test_suite () {
+ts_list () {
   grep -onE "^ *${TS_NAME:-test_\w+} +\(\)" "$@" |
   tr -d " ()" |
   tr ":" " "
@@ -159,7 +159,7 @@ H
 ts_monitor () {
 mon_file="$1"
 
-if [ "true" = "$monitor" ]
+if [ "true" = "$ts_monitor" ]
 then sed -lne "
 /^\[/ !{
 H
@@ -168,7 +168,7 @@ $ !d
 x
 1 d
 
-w $mon_file
+w $ts_mon_file
 /P\$/a\\
 .
 /F\$/a\\
@@ -180,13 +180,13 @@ n
 " | 
   tr -ud "\n" | 
     tr -u "n" "\n" >&2
-cat "$mon_file"
+cat "$ts_mon_file"
 else cat
 fi
 }
 
 ts_format () {
-if [ "true" = "$format" ]
+if [ "true" = "$ts_format" ]
 then sed -lne "
 /^\[/ !{
 H
@@ -205,7 +205,7 @@ fi
 }
 
 ts_filter () {
-if [ "true" = "$verbose" ]
+if [ "true" = "$ts_verbose" ]
 then cat
 else sed -lne "
 /^\[/ !{
@@ -222,14 +222,14 @@ fi
 }
 
 ts_process () {
-raw_file="$1"; mon_file="$2";
+ts_raw_file="$1"; ts_mon_file="$2";
 
-if [ "true" = "$raw" ]
+if [ "true" = "$ts_raw" ]
 then cat
 else   
-tee "$raw_file" |
+tee "$ts_raw_file" |
   ts_structure |
-    ts_monitor "$mon_file" |
+    ts_monitor "$ts_mon_file" |
       ts_format |
         ts_filter
 fi
@@ -252,22 +252,22 @@ teardown
 }
 
 ts_report () {
-raw_file="$1"
+ts_raw_file="$1"
 
-if [ "true" != "$raw" ]
+if [ "true" != "$ts_raw" ]
 then
-  npass="$(grep -c '^% P' "$raw_file")"
+  npass="$(grep -c '^% P' "$ts_raw_file")"
   npass=${npass:-0}
 
-  nfail="$(grep -c '^% F' "$raw_file")"
+  nfail="$(grep -c '^% F' "$ts_raw_file")"
   nfail=${nfail:-0}
 
-  nnoex="$(grep -c '^% X' "$raw_file")"
+  nnoex="$(grep -c '^% X' "$ts_raw_file")"
   nnoex=${nnoex:-0}
 
-  printf "%s pass %s fail %s s\n" "$npass" "$(($nfail + $nnoex))" "$(($end_time - $start_time))" >&2
+  printf "%s pass %s fail %s s\n" "$npass" "$(($nfail + $nnoex))" "$(($ts_end_time - $ts_start_time))" >&2
 
-  if [ "true" = "$cleanup" ]
+  if [ "true" = "$ts_cleanup" ]
   then rm -r "$TS_TMP_DIR"
   fi
 
@@ -275,23 +275,23 @@ then
 fi
 }
 
-run_ts () {
+ts_run () {
 test_file="$0"
 test_case="${test_file##*/}"
 test_case="${test_case%\.*}"
 
-if [ "true" = "$list" ]
+if [ "true" = "$ts_list" ]
 then
   ts_list "$test_file"
   exit
 fi
 
 mkdir -p "$TS_TMP_DIR"
-raw_file="$TS_TMP_DIR/$test_case.raw"
-mon_file="$TS_TMP_DIR/$test_case.mon"
+ts_raw_file="$TS_TMP_DIR/$test_case.raw"
+ts_mon_file="$TS_TMP_DIR/$test_case.mon"
 
-start_time=$SECONDS
-ts_test_suite "$test_file" |
+ts_start_time=$SECONDS
+ts_list "$test_file" |
 while read lineno test_name
 do
   test_dir="$TS_TMP_DIR/$test_case/$test_name"
@@ -300,23 +300,23 @@ do
   # * use stdout for progress, stderr for debug information
   # * a zero exit status is considered a pass, otherwise fail
   if
-    if [ "true" = "$debug" ]
+    if [ "true" = "$ts_debug" ]
     then (ts_run_test 2>&1)
     else (ts_run_test 2>/dev/null)
     fi
-  then status=P
-  else status=F
+  then ts_status=P
+  else ts_status=F
   fi
 
-  printf "%% %s [%s:%s] %s\n" "$status" "$test_file" "$lineno" "$test_name"
-done | ts_process "$raw_file" "$mon_file"
-end_time=$SECONDS
+  printf "%% %s [%s:%s] %s\n" "$ts_status" "$test_file" "$lineno" "$test_name"
+done | ts_process "$ts_raw_file" "$ts_mon_file"
+ts_end_time=$SECONDS
 
-ts_report "$raw_file"
+ts_report "$ts_raw_file"
 }
 
-run_ts_suite () {
-if [ "true" = "$list" ]
+ts_run_suite () {
+if [ "true" = "$ts_list" ]
 then
   ts_list "$@"
   exit
@@ -327,24 +327,24 @@ export TS_TMP_DIR
 export TS_NAME
 
 mkdir -p "$TS_TMP_DIR"
-main_raw_file="$TS_TMP_DIR/raw"
-main_mon_file="$TS_TMP_DIR/mon"
+ts_raw_file="$TS_TMP_DIR/raw"
+ts_mon_file="$TS_TMP_DIR/mon"
 
-start_time=$SECONDS
+ts_start_time=$SECONDS
 for test_file in "$@"
 do
   if [ -x "$test_file" ]
   then "$test_file" -r
   else printf "%% X [%s] not executable\n" "$test_file"
   fi
-done | ts_process "$main_raw_file" "$main_mon_file"
-end_time=$SECONDS
+done | ts_process "$ts_raw_file" "$ts_mon_file"
+ts_end_time=$SECONDS
 
-ts_report "$main_raw_file"
+ts_report "$ts_raw_file"
 }
 
-if [ "ts" = "$progname" ]
+if [ "ts" = "$ts_progname" ]
 then
-  run_ts_suite "$@"
+  ts_run_suite "$@"
   exit $?
 fi
