launch tests using a trap vs an explicit call to ts_run

diff --git a/bin/ts b/bin/ts
--- a/bin/ts
+++ b/bin/ts
@@ -1,11 +1,13 @@
 #!/bin/bash
 ############################################################################
+ts_progname="${0##*/}"
 ts_version="1.0"
 ts_author="Simon Chiang"
 ts_usage="usage: %s [-c] [-d] [-f] [-h] [-r] [-t TS_TMP_DIR] [-v] %s\n"
-ts_args="[TEST_FILES...]"
-ts_args="${ts_args:-[TEST_NAMES...]}"
-ts_progname="${0##*/}"
+if [ "ts" = "$ts_progname" ]
+then ts_args="[TEST_FILES...]"
+else ts_args="[TEST_NAMES...]"
+fi
 ts_opt="       %s   %s\n"
 
 while getopts "cdfhlmn:rt:v" ts_option
@@ -193,23 +195,31 @@ ts_run_test () {
   return $exitstatus
 }
 
-# Run the test files if this script is executed directly.
-if [ "ts" = "$ts_progname" ]
-then
-  export TS_USR_DIR
-  export TS_TMP_DIR
-  export TS_NAME
+ts_run_test_suite () {
+  test_file="$0"
+  test_case="${test_file##*/}"
+  test_case="${test_case%\.*}"
 
-  for test_file in "$@"
+  ts_list "$test_file" |
+  while read test_lineno test_name
   do
-    if [ -x "$test_file" ]
-    then "$test_file" -r
-    else printf "%% X [%s] not executable\n" "$test_file"
-    fi
-  done | ts_report
-  exit $?
-fi
+    test_dir="$TS_TMP_DIR/$test_case/$test_name"
 
+    # run the test by calling back into the test file
+    # * use stdout for progress, stderr for debug information
+    # * a zero exit status is considered a pass, otherwise fail
+    if
+      if [ "true" = "$ts_debug" ]
+      then (ts_run_test 2>&1)
+      else (ts_run_test 2>/dev/null)
+      fi
+    then ts_status=P
+    else ts_status=F
+    fi
+
+    printf "%% %s [%s:%s] %s\n" "$ts_status" "$test_file" "$test_lineno" "$test_name"
+  done | ts_report
+}
 ############################################################################
 setup () {
   true
@@ -287,30 +297,24 @@ assert_match () {
     exit 1
   fi
 }
-
-ts_run () {
-  test_file="$0"
-  test_case="${test_file##*/}"
-  test_case="${test_case%\.*}"
-
-  ts_list "$test_file" |
-  while read test_lineno test_name
-  do
-    test_dir="$TS_TMP_DIR/$test_case/$test_name"
-
-    # run the test by calling back into the test file
-    # * use stdout for progress, stderr for debug information
-    # * a zero exit status is considered a pass, otherwise fail
-    if
-      if [ "true" = "$ts_debug" ]
-      then (ts_run_test 2>&1)
-      else (ts_run_test 2>/dev/null)
-      fi
-    then ts_status=P
-    else ts_status=F
-    fi
-
-    printf "%% %s [%s:%s] %s\n" "$ts_status" "$test_file" "$test_lineno" "$test_name"
-  done | ts_report
-}
 ############################################################################
+
+# Run the test files if this script is executed directly. Otherwise, set a
+# trap to run the test suite after the tests have been defined.
+if [ "ts" = "$ts_progname" ]
+then
+  export TS_USR_DIR
+  export TS_TMP_DIR
+  export TS_NAME
+
+  for test_file in "$@"
+  do
+    if [ -x "$test_file" ]
+    then "$test_file" -r
+    else printf "%% X [%s] not executable\n" "$test_file"
+    fi
+  done | ts_report
+  exit $?
+else
+  trap 'ts_run_test_suite' EXIT
+fi
