sketch out fifo usage

diff --git a/bin/ts b/bin/ts
--- a/bin/ts
+++ b/bin/ts
@@ -27,11 +27,6 @@ TS_TMP_DIR="${TS_TMP_DIR:-$TS_USR_DIR/tmp}"
 TS_CLEANUP="${TS_CLEANUP:-false}"
 
 ############################################################################
-# Count the number of $1 chars on stdin
-count () {
-  grep -o "$1" | wc -l | tr -d " "
-}
-
 # Check the input stream for output in the format:
 #
 #   [test/case:10] test_name
@@ -48,20 +43,8 @@ monitor () {
   :show
   x
 
-  /P\$/a\\
-.
-  /F\$/a\\
-F
-
-  s/F\$//w $1
+  s/F\$//p
   " | tr -d "\n"
-}
-
-# Print '-' to stdout and a message to stderr.
-skip () {
-  printf "-"
-  printf "[%s] %s\n\n" "$1" "$2" >&2
-  continue
 }
 
 # Abbreviate stdin by deleting xtrace lines using PS4="$PS4-"
@@ -79,37 +62,52 @@ mkdir -p "$TS_TMP_DIR"
 TS_TMP_DIR="$(cd "$TS_TMP_DIR" || exit 1; pwd)"
 
 # Prepare log files
-log="$TS_TMP_DIR/tslog"
-err="$TS_TMP_DIR/tserr"
-rm -f "$log" "$err"
-touch "$log" "$err"
+input="$TS_TMP_DIR/input"
+output="$TS_TMP_DIR/output"
+rm -f "$input" "$output"
+mkfifo "$input"
+touch "$output"
 
 # Run the test files
+npass=0
+nfail=0
 start=$SECONDS
-for test_file in "$@"
+grep -onEH "^ *test_\w+ +\(\)" "$@" | tr -d " ()" | tr ":" " " > "$input" &
+
+while read test_file lineno test_name
 do
-  out="$TS_TMP_DIR/$(basename "$test_file").out"
-  rm -f "$out"
+  # run the test by calling back into the test file
+  # * use stdout for progress, stderr for debug information
+  # * a zero exit status is considered a pass, otherwise fail
+  printf "[$test_file:$lineno:$test_name]\n" #>&2
 
-  if ! [ -f "$test_file" ]
-  then skip "$test_file" "not a file" 2>> "$err"
-  fi
+  # if ! [ -x "$test_file" ]
+  # then 
+  #   printf "-"
+  #   printf "not executable" >&2
+  #   continue
+  # fi
 
-  if ! [ -x "$test_file" ]
-  then skip "$test_file" "not executable" 2>> "$err"
-  fi
-
-  "$test_file" 2>&1 | monitor "$out" | tee -a "$log"
-  cat "$out" | untrace >> "$err"
-done
+  # if "$test_file" "$test_name" "$lineno"
+  # then
+  #   printf "."
+  #   ((npass++))
+  # else
+  #   printf "F"
+  #   ((nfail++))
+  # fi
+done < "$input" #2>> "$output"
+exit
 end=$SECONDS
 
 # Report results
 printf "\nFinished in %ss\n\n" "$(($end - $start))"
-cat "$err" >&2
-printf "%s pass, %s fail\n" "$(count '\.' < "$log")" "$(count 'F' < "$log")"
+# cat "$output" | monitor | untrace
+printf "%s pass, %s fail\n" "$npass" "$nfail"
 
 # Cleanup
+# rm -f "$input" "$output" "$errors"
+
 if [ "true" = "$TS_CLEANUP" ]
 then rm -r "$TS_TMP_DIR"
 fi
