Get distribution tests working for non-default shells
Note there were some mistakes in the previous setup.  It was basically
starting at the non-default shell but executing tests as if the default
shell.  In order to install ksh,zsh switch to only testing on the latest
of each distro.  Developers can still check out specific distributions
using the README instructions.

diff --git a/test/distributions b/test/distributions
--- a/test/distributions
+++ b/test/distributions
@@ -1,29 +1,32 @@
 #!/bin/bash
 
 mkdir -p tmp/distributions
-while read image shells
+while read os shells
 do
+  outfile=tmp/distributions/"$image".buildlog
+  image="ts_$os"
+
+  printf "make %s ... " "$image"
+  if docker build -t "$image" dockerfiles/"$os" >"$outfile" 2>&1
+  then
+    printf "success\n"
+  else
+    printf "fail\n"
+    exit 1
+  fi
+
   for shell in $shells
   do
-    outfile=tmp/distributions/"$(tr ':' '_' <<<"$image")"_"$(basename "$shell")"
+    outfile=tmp/distributions/"$image"_"$(basename "$shell")"
 
-    printf "%s %s ... " "$image" "$shell"
+    printf "test %s %s ... " "$image" "$shell"
     ./test/distribution "$image" "$shell" >"$outfile" 2>&1
     tail -n 1 "$outfile"
   done
 done <<DOC
-centos:5 /bin/sh /bin/bash
-centos:6 /bin/sh /bin/bash
-centos:7 /bin/sh /bin/bash
-debian:7.10 /bin/sh /bin/bash
-debian:8.4 /bin/sh /bin/bash
-fedora:21 /bin/sh /bin/bash
-fedora:22 /bin/sh /bin/bash
-fedora:23 /bin/sh /bin/bash
-opensuse:13.2 /bin/sh /bin/bash
-opensuse:42.1 /bin/sh /bin/bash
-ubuntu:12.04 /bin/sh /bin/bash /bin/dash
-ubuntu:14.04 /bin/sh /bin/bash /bin/dash
-ubuntu:15.10 /bin/sh /bin/bash /bin/dash
-ubuntu:16.04 /bin/sh /bin/bash /bin/dash
+centos /bin/bash /bin/zsh /bin/ksh
+debian /bin/bash /bin/zsh /bin/ksh
+fedora /bin/bash /bin/zsh /bin/ksh
+opensuse /bin/bash /bin/zsh /bin/ksh
+ubuntu /bin/dash /bin/bash /bin/zsh /bin/ksh
 DOC
